#!/bin/bash -e

# update gsettings with customizations
glib-compile-schemas /usr/share/glib-2.0/schemas

# update db for overlayed desktop files
update-desktop-database

# make user and set ownerhip for user homedir
useradd -m user -s /bin/bash
chown -R user:user /home/user

# allow managing USB disks
gpasswd -a user plugdev
chmod o+r /etc/udiskie.conf

# create mountpoint for bitkey
mkdir /mnt/bitkey-data
chown user:user /mnt/bitkey-data

# allow webcam access for QR code reading
gpasswd -a user video

# auto login
mkdir -p /etc/systemd/system/getty@tty1.service.d
echo "[Service]" > /etc/systemd/system/getty@tty1.service.d/override.conf
echo "ExecStart=" >> /etc/systemd/system/getty@tty1.service.d/override.conf
echo "ExecStart=-/sbin/agetty --autologin user --noclear %I 38400 linux" >> /etc/systemd/system/getty@tty1.service.d/override.conf